#!/bin/bash

lolcommits &> /dev/null || exit

LOLCOMMITS_DIR=~/.lolcommits/imgs \
    lolcommits --capture --stealth --fork --delay 1 &> /dev/null &

sleep 2

LOLCOMMITS_DIR=~/.lolcommits/gifs \
    lolcommits --capture --stealth --fork --delay 1 --animate 3 &> /dev/null &