#!/bin/sh

lolcommits || exit

LOLCOMMITS_DIR=~/.lolcommits/imgs; export LOLCOMMITS_DIR
lolcommits --capture --stealth --fork --delay 1 --device /dev/video2 &

sleep 2

LOLCOMMITS_DIR=~/.lolcommits/gifs; export LOLCOMMITS_DIR
lolcommits --capture --stealth --fork --delay 1 --device /dev/video2 &